version: '3.3'  # Versión de Docker Compose

services:
  web:  # Servicio de tu aplicación FastAPI
    build: .  # Construir desde el Dockerfile en el directorio actual
    ports:
      - "8000:80"  # Mapear puerto 8000 del host al 80 del contenedor
    environment:
      - DATABASE_URL=postgresql+asyncpg://fastapi_user:password@db:5432/fastapi_db
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    #volumes:
      #- .:/app  # Montar código actual para desarrollo
    restart: unless-stopped  # Reiniciar automáticamente

  db:  # Servicio de PostgreSQL
    image: postgres:15-alpine  # Imagen oficial de PostgreSQL versión 13
    environment:
      - POSTGRES_DB=fastapi_db  # Nombre de la base de datos
      - POSTGRES_USER=fastapi_user  # Usuario
      - POSTGRES_PASSWORD=password  # Contraseña
    #ports:
      #- "5434:5434"  # Exponer puerto de PostgreSQL
    expose:
        - 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen persistente para datos
    restart: unless-stopped

volumes:
  postgres_data:  # Volumen named para persistencia de datos